name: Feature Report
description: 기능 개발 이슈 생성
title: "[FEAT] "
labels: ["feature"]
assignees: ["ydking0911"]

body:
  - type: markdown
    attributes:
      value: |
        기능 개발 이슈를 생성합니다. 아래 항목을 작성해주세요.

  - type: textarea
    id: implementation
    attributes:
      label: 구현 내용
      description: 구현할 내용을 자세히 작성해주세요.
      placeholder: 예) 사용자 인증 기능 구현
    validations:
      required: true

  - type: textarea
    id: todo
    attributes:
      label: 할 일
      description: 해당 이슈에 대해 필요한 작업목록을 작성해주세요.
      placeholder: |
        - [ ] 작업 1
        - [ ] 작업 2
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: 이슈 체크리스트
      options:
        - label: Assignees 설정
          required: true
        - label: Label 설정
          required: true